### ISSUE TITLE
Erro na renderização do background do Capítulo3.pdf

### ISSUE THREAD

**Issue by GustavoLR548** [MysteRys337/Trabalho-LDO-ML#7]
Como padrão do projeto, todos os PDFs possuem uma imagem de fundo, utilizando a biblioteca do LaTeX ```\usepackage{background}```, porém a imagem está sendo renderizada de forma incorreta:

# Como está
![fundoquebrado](https://user-images.githubusercontent.com/9157977/97452876-f4f98b80-1913-11eb-8cd7-ffa472eeb8ff.png)

# Como deveria estar

![fundocerto](https://user-images.githubusercontent.com/9157977/97452883-f75be580-1913-11eb-82d0-9263fd42bc85.png)

# Mensagem de erro

![unknown](https://user-images.githubusercontent.com/9157977/97452928-0347a780-1914-11eb-9303-9abc8ca1d065.png)

Deixarei essa tarefa para o usuário @HomeniqueM para consertar isso

**Comment by HomeniqueM** [comment]
Issue consertado no PR #8
